# EXERCONS NOUS SUR LE PRE-PROCESSING

# 1. Décrire son  jeu de données

In [78]:
# importer les librairies numpy et pandas. 
import pandas as pd
import numpy as np

In [79]:
# Lire le fichier csv dans un dataframe 
df = pd.read_csv("C:/Users/barba/Desktop/client/CEFIM/analyse_de_donnée/code/données/valeurs_manquante_exo.csv", encoding = "ISO-8859-1", delimiter = ";")

In [80]:
# Afficher les premières lignes
#De quoi s'agit-il?
df.head(10)


ID  numero_rue                    adresse  code_postale  \
0  100001000.0       104.0      rue de la forêt noire         69000   
1  100002000.0       197.0              rue de bonnel         69350   
2  100003000.0         NaN      rue de la guillotière         69210   
3  100004000.0       201.0      impasse auguste rodin         69350   
4          NaN       203.0                rue pliesse          6935   
5  100006000.0       207.0  avenue charles de gaulles         69000   
6  100007000.0         NaN       avenue de la rotonde         69210   
7  100008000.0       213.0     rue de la cornouillère         69100   
8  100009000.0       215.0        rue du général rapp         69100   

          ville occupation_des_locaux nombre_de_piece  salle_deau  prix  
0          LYON                     Y               3           1  1000  
1  VILLEURBANNE                     N               3         1.5    --  
2    VENISSIEUX                     N             NaN           1   850  
3  VILLEURBANNE                    12               1         NaN   700  
4  VILLEURBANNE                     Y               3           2  1600  
5          LYON                     Y             NaN           1   800  
6    VENISSIEUX                   NaN               2  VENISSIEUX   950  
7          BRON                     Y              --           1   NaN  
8          BRON                     Y              na           2  1800

In [81]:
#Combien y a t-il de variables ?
print(len(df.columns))
print(df.shape)
# affichez le nom des colonnes
df.columns

9
(9, 9)


Index(['ID', 'numero_rue', 'adresse', 'code_postale', 'ville',
       'occupation_des_locaux', 'nombre_de_piece', 'salle_deau', 'prix'],
      dtype='object')

In [82]:
# affichez les 2 dernières lignes 
df.tail(2)

ID  numero_rue                 adresse  code_postale ville  \
7  100008000.0       213.0  rue de la cornouillère         69100  BRON   
8  100009000.0       215.0     rue du général rapp         69100  BRON   

  occupation_des_locaux nombre_de_piece salle_deau  prix  
7                     Y              --          1   NaN  
8                     Y              na          2  1800

In [83]:
# Combien y a t-il de variables qualitatives ? Quantitatives ? sont-elles ordinales ? 
# en utilisant info() que remarquez vous?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   ID                     8 non-null      float64
 1   numero_rue             7 non-null      float64
 2   adresse                9 non-null      object 
 3   code_postale           9 non-null      int64  
 4   ville                  9 non-null      object 
 5   occupation_des_locaux  8 non-null      object 
 6   nombre_de_piece        7 non-null      object 
 7   salle_deau             8 non-null      object 
 8   prix                   8 non-null      object 
dtypes: float64(2), int64(1), object(6)
memory usage: 776.0+ bytes


# 2.  repérer les données manquantes standards

In [84]:
#ouvrez sous excel votre fichier et regardez la colonne numero_rue
#Quelles sont les valeurs nulles? 

il y a une cellule vide et une cellule NA

In [85]:
# Affichez maintenant la colonne numero_rue avec pandas
# comment les valeurs nulles sont elles écrites ?
df['numero_rue']

0    104.0
1    197.0
2      NaN
3    201.0
4    203.0
5    207.0
6      NaN
7    213.0
8    215.0
Name: numero_rue, dtype: float64

In [86]:
# affichez  les valeurs nulles de la colonne numero_rue, combien y en a t-il?est ce cohérent? 
print(df['numero_rue'].isnull())
print(df['numero_rue'].isnull().sum())

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
Name: numero_rue, dtype: bool
2


il y en a bien 2, pandas a bien reconnu les cellules vides et NA comme nulle

# 3.  repérer les données manquantes non standart

In [87]:
# concentrons nous maintenant sur la colonne 'nombre_de_piece'
#ouvrez le fichier sous excel et regardez les valeurs manquantes de cette colonne. Quelles sont-elles? 

Il y a 4 valeurs manquantes : 
- n / a
- NA
- —
- na

In [88]:
# Affichez maintenant la colonne sous pandas.
df['nombre_de_piece']

0      3
1      3
2    NaN
3      1
4      3
5    NaN
6      2
7     --
8     na
Name: nombre_de_piece, dtype: object

In [89]:
#affichez les valeurs nulles . Que remarquez vous ?
print(df['nombre_de_piece'].isnull().sum())

2


Pandas a reconnu le « NAN » et "NA" comme des valeurs manquantes.  les autres types ne sont pas reconnus,
il les prend pour des valeurs cohérentes de la colonne du nombre de pièce

Pour parer à ce genre de problème on peut faire dès le début une liste de format correspondant aux valeurs manquantes

In [90]:
#faites une liste de tous les formats non reconnus que vous avez rencontré dans le dataset
missing_values = ["n/a", "na", "--"]
# maintenant réouvrons le fichier
df = pd.read_csv("C:/Users/barba/Desktop/client/CEFIM/analyse_de_donnée/code/données/valeurs_manquante_exo.csv", encoding = "ISO-8859-1", delimiter = ";", na_values = missing_values)

In [91]:
#vérifiez si toutes les valeurs nulles sont reconnues
valeurs_manquantes = df['nombre_de_piece'].isnull().sum()
print('nbr de valeurs manquantes: ', valeurs_manquantes )
df['nombre_de_piece']

nbr de valeurs manquantes:  4


0    3.0
1    3.0
2    NaN
3    1.0
4    3.0
5    NaN
6    2.0
7    NaN
8    NaN
Name: nombre_de_piece, dtype: float64

# 4. repérer les valeurs erronées

In [92]:
#affichez la colonne 'occupation_des_locaux'.
df['occupation_des_locaux']

0      Y
1      N
2      N
3     12
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: occupation_des_locaux, dtype: object

In [93]:
# Y a t-il des valeurs nulles ? 
#Quelles sont les valeurs attendues et quel est l'effectif de chacune ? 
df['occupation_des_locaux'].value_counts()

occupation_des_locaux
Y     5
N     2
12    1
Name: count, dtype: int64

In [94]:
df['occupation_des_locaux'].isnull().sum()

1

on remarque qu'une des valeurs est numérique , alors qu'elle devrait être comptée comme une valeur nulle
ce genre de problème peut être fréquent et il est nécessaire de pouvoir le détecter 
On peut alors créer une fonction qui va permettre de faire la différence :
- si la valeur est catégorique --> on la garde et on passe à la suivante
- si la valeur est numérique --> c'est une valeur manquante --> on la remplace par NAN 

pour ce faire on peut utiliser la méthode try / exceptValueError
voici la doc python qui pourrait vous aider --> https://docs.python.org/2/tutorial/errors.html
ou encore --> https://pythonforge.com/gestion-des-erreurs-et-des-exceptions-python/

In [95]:
# commencez par faire une boucle sur chaque ligne de la colonne
#cnt=0
#for row in df['occupation_des_locaux']:
#   try:
          # on teste si c'est un nombre entier (utiliser la méthode loc  https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.DataFrame.loc.html)
          # si c'est le cas on remplace par une valeur manquante (voir doc numpy) 
#    except :
         # si ce n'est pas la cas, la valeur est une chaîne de caractère donc on passe  
         # on indente
# Vérifions si la variable numérique s'est bien transformé : 
print(df['occupation_des_locaux'])
   


0      Y
1      N
2      N
3     12
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: occupation_des_locaux, dtype: object


In [96]:
cnt=0

for row in df['occupation_des_locaux']:
    try:
        int(row)
        df.loc[cnt, 'occupation_des_locaux']=np.nan
    except ValueError:
        pass
    cnt+=1       #cnt  = cnt+1
print(df['occupation_des_locaux'])

0      Y
1      N
2      N
3    NaN
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: occupation_des_locaux, dtype: object


In [97]:
#alternatives
solution_1= df['occupation_des_locaux']
for index,valeur in solution_1.items():
    if isinstance(valeur, str) and valeur.isdigit():
        df.at[index, 'occupation_des_locaux'] = np.nan
solution_1

0      Y
1      N
2      N
3    NaN
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: occupation_des_locaux, dtype: object

In [98]:
solution_2= df['occupation_des_locaux']
for index,valeur in solution_1.items():
    if str(valeur).isdigit():
        df[index, 'occupation_des_locaux'] = np.nan
solution_2

0      Y
1      N
2      N
3    NaN
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: occupation_des_locaux, dtype: object

# 5. Vérification 

In [99]:
#Combien y a t-il de valeurs manquantes pour chaque colonne ? [ appliquez la méthode.sum()]
print(df.isnull().sum())

ID                       1
numero_rue               2
adresse                  0
code_postale             0
ville                    0
occupation_des_locaux    2
nombre_de_piece          4
salle_deau               1
prix                     2
dtype: int64


In [100]:
# Combien y a t-il de valeurs manquantes au total?  [ appliquez la méthode.sum().sum()]
print(df.isnull().sum().sum())

12


In [101]:
# Que nous apprend cette commande ? 
print(df.isnull().values.any())

True


s'il reste des valeurs manquantes, dans notre cas oui 

# 5. remplacer les valeurs manquantes avec Pandas

In [102]:
# remplacer toutes les valeurs manquantes de la colonne ID par un chiffre par défaut de code erreur '200000002'
# vérifiez (toujours ! )
df['ID']

0    100001000.0
1    100002000.0
2    100003000.0
3    100004000.0
4            NaN
5    100006000.0
6    100007000.0
7    100008000.0
8    100009000.0
Name: ID, dtype: float64

In [103]:
df['ID'] = df['ID'].fillna('200000002')

In [104]:
df['ID']

0    100001000.0
1    100002000.0
2    100003000.0
3    100004000.0
4      200000002
5    100006000.0
6    100007000.0
7    100008000.0
8    100009000.0
Name: ID, dtype: object

In [105]:
# l'expert métier vous dit que lorsque la colonne occupation_des_locaux n'est pas remplie cela signifie que le logement n'est pas occupé
# remplacez donc les valeurs manquantes de cette colonne par N
# vérifiez 
df['occupation_des_locaux']

0      Y
1      N
2      N
3    NaN
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: occupation_des_locaux, dtype: object

In [106]:
df['occupation_des_locaux'] = df['occupation_des_locaux'].fillna('N') 
df['occupation_des_locaux']

0    Y
1    N
2    N
3    N
4    Y
5    Y
6    N
7    Y
8    Y
Name: occupation_des_locaux, dtype: object

In [107]:
# pour la colonne 'nombre_de_pièce' vous avez la possibilité de remplacer les valeurs manquantes par : 
# la moyenne, la médiane ou le mode. Que choisiriez vous ?
df['nombre_de_piece']

0    3.0
1    3.0
2    NaN
3    1.0
4    3.0
5    NaN
6    2.0
7    NaN
8    NaN
Name: nombre_de_piece, dtype: float64

In [109]:
mode = df['nombre_de_piece'].mode()
mode
df['nombre_de_piece'] = df['nombre_de_piece'].fillna(int(mode)) 
df['nombre_de_piece']

C:\Users\barba\AppData\Local\Temp\ipykernel_9496\119006523.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  df['nombre_de_piece'] = df['nombre_de_piece'].fillna(int(mode))


0    3.0
1    3.0
2    3.0
3    1.0
4    3.0
5    3.0
6    2.0
7    3.0
8    3.0
Name: nombre_de_piece, dtype: float64

In [110]:
# Combien reste t-il de valeurs manquantes? 
df.isna().sum()

ID                       0
numero_rue               2
adresse                  0
code_postale             0
ville                    0
occupation_des_locaux    0
nombre_de_piece          0
salle_deau               1
prix                     2
dtype: int64

# 6. remplacer les valeurs manquantes avec Sklearn

## 6.1 le MissingIndicator

In [111]:
#importez le transformer adéquat depuis la librairie sklearn.impute 
from sklearn.impute import MissingIndicator

In [112]:
#prenons l'exemple suivant : 
X = np.array([[5, 1],
              [0, 2],
              [5, 7],
             [np.nan, np.nan]])

In [113]:
#on applique le transformer à nos données :
MissingIndicator().fit_transform(X)
# Qu'obtient -on ? 

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True]])

## 6.2 le SimpleImputer

In [114]:
#importez le transformer adéquat 
from sklearn.impute import SimpleImputer  
import numpy as np

In [115]:
#reprenons l'exemple précédent : 
print(X) 

[[ 5.  1.]
 [ 0.  2.]
 [ 5.  7.]
 [nan nan]]


In [116]:
# définissez votre transformer en ajustant les paramètres, jouez avec les différentes stratégies (mean, most_frequent ect...)
imputer = SimpleImputer(missing_values=np.nan, 
             strategy='mean')

In [117]:
#on applique le transfomer à X
imputer.fit_transform(X)

array([[5.        , 1.        ],
       [0.        , 2.        ],
       [5.        , 7.        ],
       [3.33333333, 3.33333333]])

## 6.3 le KNNImputer

In [118]:
#importez le transformer adéquat depuis la librairie sklearn.impute 
from sklearn.impute import KNNImputer     


In [119]:
#reprenons l'exemple : 
X = np.array([[5, 3, 1],
              [0, 4 , 2],
              [5, 3 , 7],
             [np.nan, 3, np.nan]])

In [120]:
# définissez votre transformer en ajustant le paramètre
imputer = KNNImputer(n_neighbors=1)

In [121]:
# Appliquez le transformer
imputer.fit_transform(X)
#Par quoi les valeurs manquantes ont-elles été remplacées?

array([[5., 3., 1.],
       [0., 4., 2.],
       [5., 3., 7.],
       [5., 3., 1.]])

# 7. Encodez vos données 

## 7.1 Encodage avec pandas

Avec Pandas il est possible d'encoder les données à l'aide de la méthode get_dummies

voici la doc associée : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html

les paramètres importants sont les suivants : 
- data = on indique le nom de notre dataframe /serie / array
- prefix = pour ajouter si l'on souhaite le nom de notre colonne. (on définit une liste avec le nom des colonnes au préalable)
- dummy_na = si l'on met True, cela retournera les valeurs manquantes dans une classe séparée. Par défaut il est à False : les valeurs manquantes sont ignorées. 
- columns = si l'on souhaite encoder le nom des colonnes 
- drop_first = c'est un booléen . s'il est à False , l'encodage est un one-hot s'il est à True l'encodage crée  k-1 dummy variables pour chaque classe. 


In [122]:
# reprenons le dataframe contenant des informations immobilières, nous allons tenter d'encoder les valeurs de la colonne ville
df['ville']

0            LYON
1    VILLEURBANNE
2      VENISSIEUX
3    VILLEURBANNE
4    VILLEURBANNE
5            LYON
6      VENISSIEUX
7            BRON
8            BRON
Name: ville, dtype: object

In [123]:
#combien y a t-il de classe?
len(df['ville'].unique())

4

In [124]:
# encoder la colonne  de sorte à avoir un encodage one_hot avec get_dummies
one_hot = pd.get_dummies(df['ville'],
                         prefix='ville',
                         drop_first=False) # dans la nvelle version pandas ajoutez dtype = int 
#affichez le résultat
one_hot

ville_BRON  ville_LYON  ville_VENISSIEUX  ville_VILLEURBANNE
0       False        True             False               False
1       False       False             False                True
2       False       False              True               False
3       False       False             False                True
4       False       False             False                True
5       False        True             False               False
6       False       False              True               False
7        True       False             False               False
8        True       False             False               False

In [125]:
#ajouter maintenant ces colonnes à votre dataset et affichez les premières lignes
one_hot_df = pd.get_dummies(df, prefix='ville', 
                            columns=['ville'], 
                            drop_first=False)
one_hot_df.head()

ID  numero_rue                adresse  code_postale  \
0  100001000.0       104.0  rue de la forêt noire         69000   
1  100002000.0       197.0          rue de bonnel         69350   
2  100003000.0         NaN  rue de la guillotière         69210   
3  100004000.0       201.0  impasse auguste rodin         69350   
4    200000002       203.0            rue pliesse          6935   

  occupation_des_locaux  nombre_de_piece salle_deau    prix  ville_BRON  \
0                     Y              3.0          1  1000.0       False   
1                     N              3.0        1.5     NaN       False   
2                     N              3.0          1   850.0       False   
3                     N              1.0        NaN   700.0       False   
4                     Y              3.0          2  1600.0       False   

   ville_LYON  ville_VENISSIEUX  ville_VILLEURBANNE  
0        True             False               False  
1       False             False                True  
2       False              True               False  
3       False             False                True  
4       False             False                True

In [126]:
# encoder la colonne  de sorte à avoir un encodage avec k-1 dummy_variable
get_dummies = pd.get_dummies(df['ville'],
                         prefix='ville',
                         drop_first=True)
#affichez le résultat
get_dummies
#Que remarquez vous? 

ville_LYON  ville_VENISSIEUX  ville_VILLEURBANNE
0        True             False               False
1       False             False                True
2       False              True               False
3       False             False                True
4       False             False                True
5        True             False               False
6       False              True               False
7       False             False               False
8       False             False               False

## 7.2 Encodage avec Sklearn

Essayons maintenant d'utiliser la librairie sklearn avec la méthode onehot

voici la doc associée : 
- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html
- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html

Pour le OneHotEncoder les paramètres importants sont les suivants : 
- categories = par défaut : 'auto' les classes sont automatiquement détectées pour chaque feature. Sinon on peut ajouter une liste définie au préalable 
- drop = par défaut on met none pour avoir un encodage onehot et garder ainsi toutes les classes dans l'encodage. Si on met first, la première classe est supprimée ce qui correspond à un encodage get_dummies
- sparse = retourne une matrice sparser (c'est à dire condensée). Par défaut c'est True

Pour le LabelBinarizer les paramètres importants sont les suivants : 
- neg_label = 0 ou 1 , par défaut c'est 0 , une valeur avec un label négatif doit être encodé 
- pos_label = 0 ou 1 , par défaut c'est 0 , une valeur avec un label positif doit être encodé 
- sparse_output = retourne une matrice sparser (c'est à dire condensée). Par défaut c'est False





In [127]:
# importer le transformer adéquat depuis la librairie sklearn.preprocessing
# Lequel choisissez vous ? Pourquoi ? 
from sklearn.preprocessing import LabelBinarizer
#from sklearn.preprocessing import OneHotEncoder

In [128]:
#définissez votre transformer en jouant sur les paramètres 
lb = LabelBinarizer(neg_label = 0,pos_label = 1,  sparse_output = False)
#OHE = OneHotEncoder()

In [129]:
#appliquez votre transformer à votre colonne 
lb.fit_transform(df['ville'])
#OHE.fit_transform(df['ville'])


array([[0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

# EXCELLENT TRAVAIL!

# 8. Mise à l'échelle des données

In [130]:
# on souhaite normaliser les colonnes 'nombre_de_piece','prix', Pourquoi ? 
# pour la suite de l'exercice on définit un nouveau dataframe avec les colonnes en question
columns = ['nombre_de_piece','prix']
df_2 = df[columns]
df_2

nombre_de_piece    prix
0              3.0  1000.0
1              3.0     NaN
2              3.0   850.0
3              1.0   700.0
4              3.0  1600.0
5              3.0   800.0
6              2.0   950.0
7              3.0     NaN
8              3.0  1800.0

In [131]:
# corrigons les valeurs nulles (sans qu'il y ait de sens métier, c'est juste pour s'entraîner ! )
# pour le nombre de pièce on choisira le mode
mode = df['nombre_de_piece'].mode()
df_2['nombre_de_piece'].fillna(mode)
df_2['nombre_de_piece']


0    3.0
1    3.0
2    3.0
3    1.0
4    3.0
5    3.0
6    2.0
7    3.0
8    3.0
Name: nombre_de_piece, dtype: float64

In [136]:
# pour le prix on prendra la moyenne du prix pour les appartements ayant le même nombre de pièces
df_mean = df_2.groupby('nombre_de_piece').mean()
df_mean
loyer = df_mean.loc[3,'prix']
loyer

1210.0

In [139]:
df_2['prix'].fillna(loyer)
df_2['prix']

0    1000.0
1    1210.0
2     850.0
3     700.0
4    1600.0
5     800.0
6     950.0
7    1210.0
8    1800.0
Name: prix, dtype: float64

## 8.1 feature scaling  avec scikit-learn

In [140]:
# importer le transformer adéquat depuis la librairie sklearn.preprocessing. Lequel choisissez vous?
from sklearn.preprocessing import StandardScaler

In [141]:
# définissez votre transformer 
scaler = StandardScaler()

In [142]:
# et appliquez le 
scaler.fit_transform(df_2)


array([[ 0.5       , -0.35534254],
       [ 0.5       ,  0.244298  ],
       [ 0.5       , -0.78365721],
       [-2.5       , -1.21197187],
       [ 0.5       ,  1.35791613],
       [ 0.5       , -0.92642876],
       [-1.        , -0.4981141 ],
       [ 0.5       ,  0.244298  ],
       [ 0.5       ,  1.92900236]])

## 8.2 feature scaling  avec pandas

In [143]:
# on définit une fonction qui va calculer la standardisation
def standardisation (df_input):
    return df_input.apply(lambda x: (x-x.mean())/ x.std(), axis=0)

standardisation(df_2)

nombre_de_piece      prix
0         0.471405 -0.335020
1         0.471405  0.230326
2         0.471405 -0.738839
3        -2.357023 -1.142658
4         0.471405  1.280256
5         0.471405 -0.873445
6        -0.942809 -0.469626
7         0.471405  0.230326
8         0.471405  1.818681

In [144]:
# A vous maintenant de trouver comment normaliser les données avec pandas ! 
# reprenez votre dataframe df_2 et normaliser les données

In [145]:
def normalisation (df_input):
    return (df_input - df_input.min()) / ( df_input.max() - df_input.min())
normalisation(df_2)


nombre_de_piece      prix
0              1.0  0.272727
1              1.0  0.463636
2              1.0  0.136364
3              0.0  0.000000
4              1.0  0.818182
5              1.0  0.090909
6              0.5  0.227273
7              1.0  0.463636
8              1.0  1.000000